import { computeSlots, buildGCalUrl, buildICS } from "@/lib/calendar-slots";
import type {
  AvailabilityRule,
  AppointmentBrief,
  CalendarBlock,
} from "@/lib/calendar-slots";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function makeRule(
  overrides: Partial<AvailabilityRule> & {
    weekday: number;
    start_time: string;
    end_time: string;
    slot_minutes: number;
  }
): AvailabilityRule {
  return {
    id: "rule-1",
    effective_from: "2020-01-01",
    effective_to: null,
    ...overrides,
  };
}

/** Monday 2024-06-10 */
const MON = new Date("2024-06-10T00:00:00");
/** Next Friday 2024-06-14 */
const FRI = new Date("2024-06-14T00:00:00");

// ─────────────────────────────────────────────────────────────────────────────
// computeSlots
// ─────────────────────────────────────────────────────────────────────────────

describe("computeSlots", () => {
  it("returns empty array when there are no rules", () => {
    const slots = computeSlots([], MON, FRI, [], []);
    expect(slots).toHaveLength(0);
  });

  it("generates slots for a single weekday rule (Monday, 30-min)", () => {
    const rule = makeRule({ weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const slots = computeSlots([rule], MON, FRI, [], []);
    expect(slots).toHaveLength(2);
    expect(slots[0].status).toBe("available");
    expect(slots[0].startsAt.getHours()).toBe(9);
    expect(slots[0].startsAt.getMinutes()).toBe(0);
    expect(slots[1].startsAt.getMinutes()).toBe(30);
  });

  it("generates slots for a 60-min rule", () => {
    const rule = makeRule({ weekday: 1, start_time: "09:00", end_time: "12:00", slot_minutes: 60 });
    const slots = computeSlots([rule], MON, FRI, [], []);
    expect(slots).toHaveLength(3);
  });

  it("does not exceed window end (no partial slots)", () => {
    // 09:00–10:30 with 60-min slots → only 1 slot (09:00-10:00); 10:00-11:00 exceeds window.
    const rule = makeRule({
      weekday: 1,
      start_time: "09:00",
      end_time: "10:30",
      slot_minutes: 60,
    });
    const slots = computeSlots([rule], MON, FRI, [], []);
    expect(slots).toHaveLength(1);
    expect(slots[0].endsAt.getHours()).toBe(10);
  });

  it("marks slot as 'requested' when a requested appointment overlaps", () => {
    const rule = makeRule({ weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    // Derive actual local slot times from a baseline run to avoid timezone mismatches.
    const baseline = computeSlots([rule], MON, FRI, [], []);
    const appt: AppointmentBrief = {
      id: "appt-1",
      starts_at: baseline[0].startsAt.toISOString(),
      ends_at: baseline[0].endsAt.toISOString(),
      status: "requested",
    };
    const [first, second] = computeSlots([rule], MON, FRI, [appt], []);
    expect(first.status).toBe("requested");
    expect(first.appointmentId).toBe("appt-1");
    expect(second.status).toBe("available");
  });

  it("marks slot as 'confirmed' when a confirmed appointment overlaps", () => {
    const rule = makeRule({ weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const baseline = computeSlots([rule], MON, FRI, [], []);
    const appt: AppointmentBrief = {
      id: "appt-2",
      starts_at: baseline[0].startsAt.toISOString(),
      ends_at: baseline[0].endsAt.toISOString(),
      status: "confirmed",
    };
    const [first] = computeSlots([rule], MON, FRI, [appt], []);
    expect(first.status).toBe("confirmed");
  });

  it("does not block slots for completed/canceled/no_show appointments", () => {
    const rule = makeRule({ weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const baseline = computeSlots([rule], MON, FRI, [], []);
    const appt: AppointmentBrief = {
      id: "appt-3",
      starts_at: baseline[0].startsAt.toISOString(),
      ends_at: baseline[0].endsAt.toISOString(),
      status: "completed",
    };
    const slots = computeSlots([rule], MON, FRI, [appt], []);
    expect(slots.every((s) => s.status === "available")).toBe(true);
  });

  it("skips slots covered by a calendar block", () => {
    const rule = makeRule({ weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const baseline = computeSlots([rule], MON, FRI, [], []);
    const block: CalendarBlock = {
      starts_at: baseline[0].startsAt.toISOString(),
      ends_at: baseline[0].endsAt.toISOString(),
    };
    const slots = computeSlots([rule], MON, FRI, [], [block]);
    expect(slots).toHaveLength(1);
    expect(slots[0].startsAt.getMinutes()).toBe(baseline[1].startsAt.getMinutes());
  });

  it("deduplicates slots generated by overlapping rules", () => {
    const r1 = makeRule({ id: "r1", weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const r2 = makeRule({ id: "r2", weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const slots = computeSlots([r1, r2], MON, FRI, [], []);
    expect(slots).toHaveLength(2); // not doubled
  });

  it("respects effective_from date — skips days before rule is active", () => {
    // Rule starts Tuesday 2024-06-11; queries from Monday.
    const rule = makeRule({
      weekday: 1, // Monday
      start_time: "09:00",
      end_time: "10:00",
      slot_minutes: 30,
      effective_from: "2024-06-17", // next Monday
    });
    const slots = computeSlots([rule], MON, FRI, [], []);
    expect(slots).toHaveLength(0);
  });

  it("respects effective_to date — skips days after rule expires", () => {
    const rule = makeRule({
      weekday: 1,
      start_time: "09:00",
      end_time: "10:00",
      slot_minutes: 30,
      effective_from: "2020-01-01",
      effective_to: "2024-06-09", // day before MON
    });
    const slots = computeSlots([rule], MON, FRI, [], []);
    expect(slots).toHaveLength(0);
  });

  it("returns slots sorted ascending by startsAt", () => {
    const r1 = makeRule({ id: "r1", weekday: 1, start_time: "14:00", end_time: "15:00", slot_minutes: 30 });
    const r2 = makeRule({ id: "r2", weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const slots = computeSlots([r1, r2], MON, FRI, [], []);
    const times = slots.map((s) => s.startsAt.getTime());
    expect(times).toEqual([...times].sort((a, b) => a - b));
  });

  it("generates slots across multiple days in the range", () => {
    // Weekday 1 (Mon) and 5 (Fri) both in [MON, FRI]
    const r1 = makeRule({ id: "r1", weekday: 1, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const r2 = makeRule({ id: "r2", weekday: 5, start_time: "09:00", end_time: "10:00", slot_minutes: 30 });
    const slots = computeSlots([r1, r2], MON, FRI, [], []);
    expect(slots).toHaveLength(4); // 2 Mon + 2 Fri
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// buildGCalUrl
// ─────────────────────────────────────────────────────────────────────────────

describe("buildGCalUrl", () => {
  const params = {
    title: "Cita en Coordinación",
    startsAt: new Date("2024-06-10T09:00:00Z"),
    endsAt: new Date("2024-06-10T09:30:00Z"),
  };

  it("returns a URL starting with the Google Calendar base", () => {
    const url = buildGCalUrl(params);
    expect(url).toMatch(/^https:\/\/calendar\.google\.com\/calendar\/r\/eventedit/);
  });

  it("includes encoded title in the 'text' parameter", () => {
    const url = buildGCalUrl(params);
    expect(url).toContain("text=");
    // URLSearchParams encodes spaces as '+'; replace before decoding.
    expect(decodeURIComponent(url.replace(/\+/g, " "))).toContain("Cita en Coordinación");
  });

  it("includes a 'dates' parameter in UTC compact format", () => {
    const url = buildGCalUrl(params);
    expect(url).toContain("dates=20240610T090000Z");
  });

  it("includes optional description when provided", () => {
    const url = buildGCalUrl({ ...params, description: "My note" });
    expect(decodeURIComponent(url.replace(/\+/g, " "))).toContain("My note");
  });

  it("includes optional location when provided", () => {
    const url = buildGCalUrl({ ...params, location: "Escuela" });
    expect(decodeURIComponent(url)).toContain("Escuela");
  });

  it("omits description and location when not provided", () => {
    const url = buildGCalUrl(params);
    expect(url).not.toContain("details=");
    expect(url).not.toContain("location=");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// buildICS
// ─────────────────────────────────────────────────────────────────────────────

describe("buildICS", () => {
  const params = {
    uid: "test-uid-123",
    title: "Cita Escolar",
    startsAt: new Date("2024-06-10T09:00:00Z"),
    endsAt: new Date("2024-06-10T09:30:00Z"),
  };

  it("starts with BEGIN:VCALENDAR and ends with END:VCALENDAR", () => {
    const ics = buildICS(params);
    expect(ics.startsWith("BEGIN:VCALENDAR")).toBe(true);
    expect(ics.trimEnd().endsWith("END:VCALENDAR")).toBe(true);
  });

  it("includes VEVENT block", () => {
    const ics = buildICS(params);
    expect(ics).toContain("BEGIN:VEVENT");
    expect(ics).toContain("END:VEVENT");
  });

  it("includes UID property", () => {
    const ics = buildICS(params);
    expect(ics).toContain("UID:test-uid-123");
  });

  it("includes SUMMARY with the title", () => {
    const ics = buildICS(params);
    expect(ics).toContain("SUMMARY:Cita Escolar");
  });

  it("includes DTSTART in UTC compact format", () => {
    const ics = buildICS(params);
    expect(ics).toContain("DTSTART:20240610T090000Z");
  });

  it("includes DTEND in UTC compact format", () => {
    const ics = buildICS(params);
    expect(ics).toContain("DTEND:20240610T093000Z");
  });

  it("includes optional DESCRIPTION when provided", () => {
    const ics = buildICS({ ...params, description: "Appointment note" });
    expect(ics).toContain("DESCRIPTION:");
    expect(ics).toContain("Appointment note");
  });

  it("uses CRLF line endings (\\r\\n)", () => {
    const ics = buildICS(params);
    expect(ics).toContain("\r\n");
  });

  it("folds lines longer than 75 characters", () => {
    const longTitle = "A".repeat(200);
    const ics = buildICS({ ...params, title: longTitle });
    const lines = ics.split("\r\n");
    for (const line of lines) {
      expect(line.length).toBeLessThanOrEqual(75);
    }
  });
});
