import { defaultLocale, translate } from "@/lib/i18n";
import { StaffCalendarPage } from "./StaffCalendarPage";

export default function StaffCalendarRoute() {
  const locale = defaultLocale;

  const labels = {
    title: translate(locale, "platform.calendar.staff.title"),
    subtitle: translate(locale, "platform.calendar.staff.subtitle"),
    loading: translate(locale, "platform.calendar.loading"),
    error: translate(locale, "platform.calendar.error"),
    noCalendar: translate(locale, "platform.calendar.staff.noCalendar"),
    tabs: {
      availability: translate(locale, "platform.calendar.staff.tabs.availability"),
      blocks: translate(locale, "platform.calendar.staff.tabs.blocks"),
      appointments: translate(locale, "platform.calendar.staff.tabs.appointments"),
      calendar: translate(locale, "platform.calendar.staff.tabs.calendar"),
      school: translate(locale, "platform.calendar.staff.tabs.school"),
    },
    calendarGrid: {
      viewMonth: translate(locale, "platform.calendar.grid.viewMonth"),
      viewWeek: translate(locale, "platform.calendar.grid.viewWeek"),
      today: translate(locale, "platform.calendar.grid.today"),
      weekdaysShort: [
        translate(locale, "platform.calendar.grid.weekdays.sun"),
        translate(locale, "platform.calendar.grid.weekdays.mon"),
        translate(locale, "platform.calendar.grid.weekdays.tue"),
        translate(locale, "platform.calendar.grid.weekdays.wed"),
        translate(locale, "platform.calendar.grid.weekdays.thu"),
        translate(locale, "platform.calendar.grid.weekdays.fri"),
        translate(locale, "platform.calendar.grid.weekdays.sat"),
      ],
      statusLabels: {
        requested: translate(locale, "platform.calendar.appointment.status.requested"),
        confirmed:  translate(locale, "platform.calendar.appointment.status.confirmed"),
        completed:  translate(locale, "platform.calendar.appointment.status.completed"),
        canceled:   translate(locale, "platform.calendar.appointment.status.canceled"),
        no_show:    translate(locale, "platform.calendar.appointment.status.noShow"),
      },
      roleLabels: {
        school_owner: translate(locale, "platform.calendar.role.school_owner"),
        direction:    translate(locale, "platform.calendar.role.direction"),
        coordination: translate(locale, "platform.calendar.role.coordination"),
        teacher:      translate(locale, "platform.calendar.role.teacher"),
        clerk:        translate(locale, "platform.calendar.role.clerk"),
        student:      translate(locale, "platform.calendar.role.student"),
      },
    },
    schoolCalendar: {
      loading: translate(locale, "platform.calendar.school.loading"),
      error:   translate(locale, "platform.calendar.school.error"),
      empty:   translate(locale, "platform.calendar.school.empty"),
      addEvent: translate(locale, "platform.calendar.school.addEvent"),
      form: {
        title:               translate(locale, "platform.calendar.school.form.title"),
        titlePlaceholder:    translate(locale, "platform.calendar.school.form.titlePlaceholder"),
        description:         translate(locale, "platform.calendar.school.form.description"),
        descriptionPlaceholder: translate(locale, "platform.calendar.school.form.descriptionPlaceholder"),
        startsAt:            translate(locale, "platform.calendar.school.form.startsAt"),
        endsAt:              translate(locale, "platform.calendar.school.form.endsAt"),
        save:                translate(locale, "platform.calendar.school.form.save"),
        saving:              translate(locale, "platform.calendar.school.form.saving"),
        cancel:              translate(locale, "platform.calendar.school.form.cancel"),
        deleteButton:        translate(locale, "platform.calendar.school.form.deleteButton"),
        deleteConfirm:       translate(locale, "platform.calendar.school.form.deleteConfirm"),
        createError:         translate(locale, "platform.calendar.school.form.createError"),
        deleteError:         translate(locale, "platform.calendar.school.form.deleteError"),
        editHeading:         translate(locale, "platform.calendar.school.form.editHeading"),
        newHeading:          translate(locale, "platform.calendar.school.form.newHeading"),
        notifyParents:       translate(locale, "platform.calendar.school.form.notifyParents"),
        notifyDayOf:         translate(locale, "platform.calendar.school.form.notifyDayOf"),
      },
      eventType: {
        school_event:      translate(locale, "platform.calendar.school.eventType.school_event"),
        student_birthday:  translate(locale, "platform.calendar.school.eventType.student_birthday"),
        staff_birthday:    translate(locale, "platform.calendar.school.eventType.staff_birthday"),
      },
    },
    availability: {
      heading: translate(locale, "platform.calendar.staff.availability.heading"),
      empty: translate(locale, "platform.calendar.staff.availability.empty"),
      addButton: translate(locale, "platform.calendar.staff.availability.addButton"),
      weekday: translate(locale, "platform.calendar.staff.availability.weekday"),
      startTime: translate(locale, "platform.calendar.staff.availability.startTime"),
      endTime: translate(locale, "platform.calendar.staff.availability.endTime"),
      slotDuration: translate(locale, "platform.calendar.staff.availability.slotDuration"),
      slotDuration30: translate(locale, "platform.calendar.staff.availability.slotDuration30"),
      slotDuration60: translate(locale, "platform.calendar.staff.availability.slotDuration60"),
      effectiveFrom: translate(locale, "platform.calendar.staff.availability.effectiveFrom"),
      effectiveTo: translate(locale, "platform.calendar.staff.availability.effectiveTo"),
      effectiveToOptional: translate(locale, "platform.calendar.staff.availability.effectiveToOptional"),
      save: translate(locale, "platform.calendar.staff.availability.save"),
      saving: translate(locale, "platform.calendar.staff.availability.saving"),
      cancel: translate(locale, "platform.calendar.staff.availability.cancel"),
      deleteButton: translate(locale, "platform.calendar.staff.availability.deleteButton"),
      deleteConfirm: translate(locale, "platform.calendar.staff.availability.deleteConfirm"),
      createError: translate(locale, "platform.calendar.staff.availability.createError"),
      deleteError: translate(locale, "platform.calendar.staff.availability.deleteError"),
      weekdays: {
        0: translate(locale, "platform.calendar.staff.availability.weekdays.0"),
        1: translate(locale, "platform.calendar.staff.availability.weekdays.1"),
        2: translate(locale, "platform.calendar.staff.availability.weekdays.2"),
        3: translate(locale, "platform.calendar.staff.availability.weekdays.3"),
        4: translate(locale, "platform.calendar.staff.availability.weekdays.4"),
        5: translate(locale, "platform.calendar.staff.availability.weekdays.5"),
        6: translate(locale, "platform.calendar.staff.availability.weekdays.6"),
      },
    },
    blocks: {
      heading: translate(locale, "platform.calendar.staff.blocks.heading"),
      empty: translate(locale, "platform.calendar.staff.blocks.empty"),
      addButton: translate(locale, "platform.calendar.staff.blocks.addButton"),
      startsAt: translate(locale, "platform.calendar.staff.blocks.startsAt"),
      endsAt: translate(locale, "platform.calendar.staff.blocks.endsAt"),
      reason: translate(locale, "platform.calendar.staff.blocks.reason"),
      reasonPlaceholder: translate(locale, "platform.calendar.staff.blocks.reasonPlaceholder"),
      save: translate(locale, "platform.calendar.staff.blocks.save"),
      saving: translate(locale, "platform.calendar.staff.blocks.saving"),
      cancel: translate(locale, "platform.calendar.staff.blocks.cancel"),
      deleteButton: translate(locale, "platform.calendar.staff.blocks.deleteButton"),
      createError: translate(locale, "platform.calendar.staff.blocks.createError"),
      deleteError: translate(locale, "platform.calendar.staff.blocks.deleteError"),
    },
    appointments: {
      heading: translate(locale, "platform.calendar.staff.appointments.heading"),
      empty: translate(locale, "platform.calendar.staff.appointments.empty"),
      requested: translate(locale, "platform.calendar.appointment.status.requested"),
      confirmed: translate(locale, "platform.calendar.appointment.status.confirmed"),
      completed: translate(locale, "platform.calendar.appointment.status.completed"),
      canceled: translate(locale, "platform.calendar.appointment.status.canceled"),
      noShow: translate(locale, "platform.calendar.appointment.status.noShow"),
      approveButton: translate(locale, "platform.calendar.staff.appointments.approveButton"),
      rejectButton: translate(locale, "platform.calendar.staff.appointments.rejectButton"),
      completeButton: translate(locale, "platform.calendar.staff.appointments.completeButton"),
      noShowButton: translate(locale, "platform.calendar.staff.appointments.noShowButton"),
      addNoteButton: translate(locale, "platform.calendar.staff.appointments.addNoteButton"),
      noteBody: translate(locale, "platform.calendar.staff.appointments.noteBody"),
      noteBodyPlaceholder: translate(locale, "platform.calendar.staff.appointments.noteBodyPlaceholder"),
      outcome: translate(locale, "platform.calendar.staff.appointments.outcome"),
      includeInRecord: translate(locale, "platform.calendar.staff.appointments.includeInRecord"),
      saveNote: translate(locale, "platform.calendar.staff.appointments.saveNote"),
      savingNote: translate(locale, "platform.calendar.staff.appointments.savingNote"),
      cancelNote: translate(locale, "platform.calendar.staff.appointments.cancelNote"),
      actionError: translate(locale, "platform.calendar.staff.appointments.actionError"),
      noteError: translate(locale, "platform.calendar.staff.appointments.noteError"),
      requesterNote: translate(locale, "platform.calendar.staff.appointments.requesterNote"),
      linkedStudent: translate(locale, "platform.calendar.staff.appointments.linkedStudent"),
      filterAll: translate(locale, "platform.calendar.staff.appointments.filterAll"),
      filterPending: translate(locale, "platform.calendar.staff.appointments.filterPending"),
      filterConfirmed: translate(locale, "platform.calendar.staff.appointments.filterConfirmed"),
      filterCompleted: translate(locale, "platform.calendar.staff.appointments.filterCompleted"),
    },
  };

  return <StaffCalendarPage labels={labels} />;
}
